scripts/matchmaking_controller/init
scripts/timer_controller/init
scripts/ui_controller/init
matchmaking_plus/init
ping_monitor/init
auto_login/init
chat_extensions/init
damage_score/init
spell_log/init
spectator_mod/init
FlappyWizard/init
